version: '3'
services:
  api:
    image: cogs-api
    ports: 
      - "5000:80"
    
  db:
    image: postgres:9.6 # Should match version used for Aurora DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cogs