LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:               
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

 CcgWorksSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:             
      SecurityGroupIngress:      
        - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup 
          IpProtocol: -1
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

CcgWorksAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ccgworks-alb
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup      

  CcgWorksALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'CcgWorksTargetGroup'
      LoadBalancerArn: !Ref 'CcgWorksAlb'
      Port: '80'
      Protocol: HTTP    

  ApiALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: CcgWorksALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'CcgWorksTargetGroup'
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref 'CcgWorksALBListener'
      Priority: 1

  CcgWorksTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: CcgWorksAlb
    Properties:
      Name: !Sub ccgworks-target-group
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /health-check
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref EcsLaunchConfig
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1      
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'

  EcsLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      # Omit KeyName to prevent SSH
      ImageId: ami-a44db8c3
      SecurityGroups:
        - !Ref CcgWorksSecurityGroup
      InstanceType: !Ref 'InstanceType'
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # register with ECS cluster
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ECSAutoScalingGroup --region ${AWS::Region}

  CcgWorksService:
    Type: AWS::ECS::Service
    DependsOn: CcgWorksALBListener
    Properties:
      # Use default AWSServiceRoleForECS service-linked role
      ServiceName: !Sub ccgworks-ecs
      Cluster: !Ref 'ECSCluster'
      DesiredCount: '1'
      LoadBalancers:
        - ContainerName: CcgWorksApi
          ContainerPort: '80'
          TargetGroupArn: !Ref 'CcgWorksTargetGroup'
      TaskDefinition: !Ref 'CcgWorksTaskDefinition'

  CcgWorksTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ccgworks-task
      ContainerDefinitions:
        - Name: CcgWorksApi
          Essential: 'true'
          Image: 848502523218.dkr.ecr.eu-west-2.amazonaws.com/ccgworks:api-0.1
          MemoryReservation: 1024
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'CloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: Api
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: HOST
              Value: AWS
  
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - CcgWorksRole